SELECT * FROM CUSTOMERS;


-- 현재 목록에서 ROWNUM만 추가.
SELECT ROWNUM AS "NO.",C.*
FROM CUSTOMERS C
;


-- ROWNUM 역순 정렬
SELECT ROWNUM AS "NO.",C.*
FROM CUSTOMERS C
ORDER BY ROWNUM DESC
;

-- 페이지사이즈(5) 만큼만 출력한다
SELECT *
FROM (SELECT ROWNUM AS RNUM,C.* 
    FROM CUSTOMERS C 
    ORDER BY ROWNUM DESC)
WHERE RNUM BETWEEN 28 AND 32 
;


SELECT T2.*
FROM (SELECT ROWNUM R2,T.*
    FROM (SELECT ROWNUM AS RNUM,C.* 
        FROM CUSTOMERS C 
        ORDER BY ROWNUM DESC)T) T2
WHERE R2 BETWEEN 1 AND 5
;
