create SEQUENCE EMP_SEQ
START WITH 1000;

INSERT INTO EMPLOYEES(EMPLOYEE_ID,MANAGER,NAME,BIRTH_DATE,PHOTO,NOTES)
VALUES(EMP_SEQ.NEXTVAL,'MANAGER','±è°æ¹Î','920901','KIM.JPG','¸Å´ÏÀú');

SELECT * FROM EMPLOYEES;