-- 468명
SELECT COUNT(*)
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC
;

-- 1단계
SELECT P.BIRTH_DATE 생년월일, P.PLAYER_NAME
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC
;

-- 2단계 : 랜덤값으로 출력된다 : ROWNUM -> RESULTSET
SELECT P.BIRTH_DATE 생년월일, P.PLAYER_NAME
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL AND
    ROWNUM BETWEEN 1 AND 5
ORDER BY P.BIRTH_DATE DESC
;

-- 3단계 : 정렬 후 ROWNUM
SELECT ROWNUM AS "NO.",P.BIRTH_DATE 생년월일, P.PLAYER_NAME
FROM (SELECT P.BIRTH_DATE, P.PLAYER_NAME
    FROM PLAYER P
    WHERE P.BIRTH_DATE IS NOT NULL
    ORDER BY P.BIRTH_DATE DESC) P 
WHERE ROWNUM BETWEEN 1 AND 5
;

-- 2페이지
SELECT RNUM AS "NO.",P.BIRTH_DATE 생년월일, P.PLAYER_NAME 
FROM (SELECT ROWNUM RNUM,P.BIRTH_DATE, P.PLAYER_NAME 
    FROM (SELECT P.BIRTH_DATE, P.PLAYER_NAME
        FROM PLAYER P
        WHERE P.BIRTH_DATE IS NOT NULL 
        ORDER BY P.BIRTH_DATE DESC ) P ) P
WHERE RNUM BETWEEN 1 AND 10
ORDER BY RNUM ASC
;


